export const SET_EDIT_ISSUE = 'SET_EDIT_ISSUE';
export const EDIT_ISSUE_REQUEST = 'EDIT_ISSUE_REQUEST';
export const EDIT_ISSUE_SUCCESS = 'EDIT_ISSUE_SUCCESS';
export const EDIT_ISSUE_FAIL = 'EDIT_ISSUE_FAIL';
